### ISSUE TITLE
怎么自动更新到新版本

### ISSUE THREAD

**Issue by Baikele** [Willh92/GameWxQRlogin#2]
大佬可以告知一下么？

**Comment by Willh92** [comment]
没有自动更新功能，release页面的版本就是最新的，要是登录不上看说明，部分软件需要先在软件内点击登录跳转到微信，再到软件扫码才能正常登录

**Comment by Baikele** [comment]
> 没有自动更新能力，功能页面的版本就是最新的，如果登录不上看说明，部分软件需要先在软件内点击登录跳转到微信，再到软件扫描码正常登录

可以增加一个更新跳转么？版本更新跳转到指定连接

**Comment by Willh92** [comment]
- 下个版本加> > 没有自动更新能力，功能页面的版本就是最新的，如果登录不上看说明，部分软件需要先在软件内点击登录跳转到微信，再到软件扫描码正常登录
> 
> 
> 
> 可以增加一个更新跳转么？版本更新跳转到指定连接

**Comment by Willh92** [comment]
下个版本加
> 可以增加一个更新跳转么？版本更新跳转到指定连接

**Comment by Willh92** [comment]
closed #2

**Comment by Willh92** [comment]
[](https://github.com/Willh92/GameWxQRlogin/releases/tag/1.4.2)

**Comment by Baikele** [comment]
> 添加更新提醒[1.4.2](https://github.com/Willh92/GameWxQRlogin/releases/tag/1.4.2)

似乎并不会更新

**Comment by Willh92** [comment]
> > 添加更新提醒[1.4.2](https://github.com/Willh92/GameWxQRlogin/releases/tag/1.4.2)
> 
> 似乎并不会更新

1.4.2以后的版本才会有提醒

**Comment by Baikele** [comment]
> > > 添加更新提醒[1.4.2](https://github.com/Willh92/GameWxQRlogin/releases/tag/1.4.2)
> > 
> > 
> > 似乎并不会更新
> 
> 1.4.2以后的版本才会有提醒

我自己构建了一份并且，v.json里面的versionname更改为了1.4.3
还是无法更新

**Comment by Willh92** [comment]
> > > > 添加更新提醒[1.4.2](https://github.com/Willh92/GameWxQRlogin/releases/tag/1.4.2)
> > > 
> > > 
> > > 似乎并不会更新
> > 
> > 
> > 1.4.2以后的版本才会有提醒
> 
> 我自己构建了一份并且，v.json里面的versionname更改为了1.4.3 还是无法更新

versionCode判断的，不是versionName

**Comment by Baikele** [comment]
> > > > > 添加更新提醒[1.4.2](https://github.com/Willh92/GameWxQRlogin/releases/tag/1.4.2)
> > > > 
> > > > 
> > > > 看起来并不会更新
> > > 
> > > 
> > > 1.2.2以后的版本会有4.提醒
> > 
> > 
> > 我自己制作了一个并且更新了，v.json里面的版本名改变了1.4.3还是无法更新
> 
> versionCode的判断，不是versionName

哦哦，好的，谢谢啊
