### ISSUE TITLE
无法登陆腾讯视频

### ISSUE THREAD

**Issue by Baikele** [Willh92/GameWxQRlogin#4]
腾讯视频无法登陆

**Comment by Willh92** [comment]
1.打开要登录的应用，注销当前登录，有用户协议就勾选，点击微信登录
2.跳转到微信后（不要点授权确定），打开或切换到扫码APP，出现二维码后点击分享给对方。
3.在扫码APP内等待对方扫码授权，成功授权后会自动跳转登录。
