### ISSUE TITLE
适配一下腾讯手游加速器吧

### ISSUE THREAD

**Issue by jeraypop** [Willh92/GameWxQRlogin#6]
看了列表有王者营地,没有腾讯手游加速器

**Comment by jeraypop** [comment]
嗯,我也试了很多次,不成功, 有时间看一下,这个应用名字叫:   TaiQ    看看行不行  腾讯的一个机器人App

**Comment by jeraypop** [comment]
嗯,我也试了很多次,不成功, 有时间看一下,这个应用名字叫:   TaiQ    看看行不行  腾讯的一个机器人App

**Comment by Willh92** [comment]
已添加，TaiQ可以的
