### ISSUE TITLE
扫码成功是怎么回调的

### ISSUE THREAD

**Issue by RavenCri** [Willh92/GameWxQRlogin#7]
有个疑问，手机扫码上面的二维码之后，app如何获取的登陆信息，如何感知到登陆成功的。是微信推送的吗？安卓不太懂，大佬看到希望回复一下~

**Comment by shsq666** [comment]
有快手的吗

**Comment by Willh92** [comment]
Web端会监听扫码，成功后会有个授权Token，通过隐式Intent传递唤起对应App> 有个疑问，手机扫码上面的二维码之后，app如何获取的登陆信息，如何感知到登陆成功的。是微信推送的吗？安卓不太懂，大佬看到希望回复一下~

**Comment by RavenCri** [comment]
监听代码位于mainActivity.java中吗
我看了里面有三处js代码。好像没看到监听的内容😀

**Comment by Willh92** [comment]
是web上面的监听，开启webview的调试，或者你在[pc访问这个](https://q.willh.cn)浏览器调试也看得见

**Comment by Willh92** [comment]
是web上面的监听，开启webview的调试，或者你在[pc访问这个](https://q.willh.cn)浏览器调试也看得见
